quarkus.couchbase.username=Administrator
quarkus.couchbase.password=password
quarkus.couchbase.connection-string=localhost
quarkus.devservices.enabled=false
quarkus.grpc.server.port=8060
quarkus.grpc.server.use-separate-server=true
quarkus.application.name=quarformer

quarkus.generate-code.grpc.scan-for-imports=all
